/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AsciiDocAutoPreviewPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  delay: 1e3,
  enabled: true
};
var AsciiDocAutoPreviewPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.debouncedRefresh = null;
  }
  async onload() {
    await this.loadSettings();
    this.buildDebouncer();
    this.registerEvent(
      this.app.workspace.on("editor-change", () => {
        var _a;
        if (!this.settings.enabled) return;
        const activeFile = this.app.workspace.getActiveFile();
        if (activeFile && activeFile.extension === "adoc") {
          (_a = this.debouncedRefresh) == null ? void 0 : _a.call(this);
        }
      })
    );
    this.addCommand({
      id: "toggle-auto-preview",
      name: "Toggle auto preview",
      callback: () => {
        this.settings.enabled = !this.settings.enabled;
        this.saveSettings();
        new import_obsidian.Notice(
          `AsciiDoc Auto Preview ${this.settings.enabled ? "enabled" : "disabled"}`
        );
      }
    });
    this.addCommand({
      id: "refresh-preview-now",
      name: "Refresh AsciiDoc preview now",
      callback: () => {
        this.refreshPreview();
      }
    });
    this.addSettingTab(new AsciiDocAutoPreviewSettingTab(this.app, this));
  }
  buildDebouncer() {
    this.debouncedRefresh = (0, import_obsidian.debounce)(
      () => this.refreshPreview(),
      this.settings.delay,
      true
    );
  }
  async refreshPreview() {
    var _a, _b, _c;
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile || activeFile.extension !== "adoc") return;
    const commandIds = [
      "asciidoc:reload-preview",
      "asciidoc:refresh-preview",
      "asciidoc:reload",
      "asciidoc-plugin:reload-preview",
      "asciidoc-preview:reload"
    ];
    const allCommands = (_b = (_a = this.app.commands) == null ? void 0 : _a.commands) != null ? _b : {};
    for (const cmdId of commandIds) {
      if (allCommands[cmdId]) {
        this.app.commands.executeCommandById(cmdId);
        return;
      }
    }
    const viewTypes = [
      "asciidoc",
      "asciidoc-preview",
      "adoc-preview",
      "asciidoc-view",
      "adoc"
    ];
    for (const type of viewTypes) {
      const leaves = this.app.workspace.getLeavesOfType(type);
      for (const leaf of leaves) {
        const view = leaf.view;
        if (view == null ? void 0 : view.render) {
          view.render();
          return;
        }
        if (view == null ? void 0 : view.refresh) {
          view.refresh();
          return;
        }
        if (view == null ? void 0 : view.reload) {
          view.reload();
          return;
        }
      }
    }
    this.app.workspace.iterateAllLeaves((leaf) => {
      const view = leaf.view;
      const leafFile = view == null ? void 0 : view.file;
      if ((leafFile == null ? void 0 : leafFile.path) === activeFile.path) {
        if (view == null ? void 0 : view.render) view.render();
        else if (view == null ? void 0 : view.refresh) view.refresh();
        else if (view == null ? void 0 : view.onLoadFile) view.onLoadFile(activeFile);
      }
    });
    (_c = this.app.metadataCache) == null ? void 0 : _c.trigger("changed", activeFile);
    this.app.vault.trigger("modify", activeFile);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  onunload() {
    this.debouncedRefresh = null;
  }
};
var AsciiDocAutoPreviewSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "AsciiDoc Auto Preview Settings" });
    new import_obsidian.Setting(containerEl).setName("Refresh delay (ms)").setDesc("Milliseconds of inactivity before the preview is refreshed").addText(
      (text) => text.setPlaceholder("1000").setValue(this.plugin.settings.delay.toString()).onChange(async (value) => {
        const parsed = parseInt(value);
        this.plugin.settings.delay = isNaN(parsed) || parsed < 100 ? 1e3 : parsed;
        this.plugin.buildDebouncer();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Enable auto preview").setDesc("Automatically refresh the AsciiDoc preview when you stop typing").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enabled).onChange(async (value) => {
        this.plugin.settings.enabled = value;
        await this.plugin.saveSettings();
      })
    );
  }
};
